# Generated by Django 3.1.5 on 2021-01-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=set(),
        ),
    ]
